#!/bin/bash
# RIGOR — Project Setup Script
# Generated by: Architect (Gemini CLI)
# Executed by: Builder (OpenCode CLI)
# 
# This script creates the complete monorepo structure
# and configures all necessary files.

set -e  # Exit on any error

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏗️  RIGOR — Project Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script will create:"
echo "  - Monorepo structure"
echo "  - Astro landing app"
echo "  - VitePress docs app"
echo "  - Shared design tokens package"
echo ""

# ============================================
# STEP 1: Create Directory Structure
# ============================================
echo "📁 Creating monorepo structure..."

mkdir -p rigor
cd rigor

mkdir -p apps/web/src/{components,layouts,pages,styles}
mkdir -p apps/web/public/diagrams
mkdir -p apps/docs/.vitepress/theme
mkdir -p apps/docs/{specification,implementation,examples,public}
mkdir -p packages/design-tokens/css

echo "   ✓ Directories created"

# ============================================
# STEP 2: Root Package Configuration
# ============================================
echo ""
echo "📦 Creating root package.json..."

cat > package.json << 'EOF'
{
  "name": "rigor-monorepo",
  "version": "0.1.0",
  "private": true,
  "description": "RIGOR — AI Constraint Protocol",
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "scripts": {
    "dev": "turbo run dev",
    "build": "turbo run build",
    "dev:web": "turbo run dev --filter=web",
    "dev:docs": "turbo run dev --filter=docs",
    "build:web": "turbo run build --filter=web",
    "build:docs": "turbo run build --filter=docs"
  },
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=9.0.0"
  }
}
EOF

echo "   ✓ Root package.json created"

# ============================================
# STEP 3: Turborepo Configuration
# ============================================
echo ""
echo "⚡ Creating turbo.json..."

cat > turbo.json << 'EOF'
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "dev": {
      "cache": false,
      "persistent": true
    },
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".astro/**", ".vitepress/dist/**"]
    }
  }
}
EOF

echo "   ✓ Turbo config created"

# ============================================
# STEP 4: Design Tokens Package
# ============================================
echo ""
echo "🎨 Setting up design tokens package..."

cd packages/design-tokens

cat > package.json << 'EOF'
{
  "name": "@rigor/design-tokens",
  "version": "0.1.0",
  "private": true,
  "description": "RIGOR design tokens - Visual Identity System v0.1",
  "main": "./tokens.json",
  "exports": {
    ".": "./tokens.json",
    "./css": "./css/variables.css",
    "./tailwind": "./tailwind.config.js"
  }
}
EOF

# Copy design tokens from project-brief
# Note: Adjust path based on where project-brief is located
BRIEF_PATH="../../project-brief"

if [ -f "$BRIEF_PATH/4-assets/design-tokens/tokens.json" ]; then
  cp "$BRIEF_PATH/4-assets/design-tokens/tokens.json" .
  cp "$BRIEF_PATH/4-assets/design-tokens/variables.css" css/
  cp "$BRIEF_PATH/4-assets/design-tokens/tailwind-preset.js" tailwind.config.js
  echo "   ✓ Design tokens copied from project-brief"
else
  echo "   ⚠️  Warning: project-brief not found, design tokens not copied"
  echo "   You'll need to manually copy files from:"
  echo "   - project-brief/4-assets/design-tokens/tokens.json"
  echo "   - project-brief/4-assets/design-tokens/variables.css"
  echo "   - project-brief/4-assets/design-tokens/tailwind-preset.js"
fi

cd ../..

# ============================================
# STEP 5: Astro Web App
# ============================================
echo ""
echo "🚀 Setting up Astro web app..."

cd apps/web

cat > package.json << 'EOF'
{
  "name": "web",
  "type": "module",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview"
  },
  "dependencies": {
    "@rigor/design-tokens": "*",
    "astro": "^4.0.0",
    "@astrojs/tailwind": "^5.0.0",
    "tailwindcss": "^3.4.0"
  }
}
EOF

cat > astro.config.mjs << 'EOF'
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  output: 'static',
  integrations: [tailwind()],
  site: 'https://rigor.dev',
});
EOF

cat > tailwind.config.mjs << 'EOF'
import rigorPreset from '@rigor/design-tokens/tailwind';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  presets: [rigorPreset],
}
EOF

cat > tsconfig.json << 'EOF'
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  }
}
EOF

# Create placeholder index page
cat > src/pages/index.astro << 'EOF'
---
// Placeholder - will be replaced by builders
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>RIGOR — AI Constraint Protocol</title>
  </head>
  <body>
    <h1>RIGOR</h1>
    <p>Setup complete. Awaiting component implementation.</p>
  </body>
</html>
EOF

echo "   ✓ Astro app configured"

cd ../..

# ============================================
# STEP 6: VitePress Docs App
# ============================================
echo ""
echo "📚 Setting up VitePress docs app..."

cd apps/docs

cat > package.json << 'EOF'
{
  "name": "docs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vitepress dev",
    "build": "vitepress build",
    "preview": "vitepress preview"
  },
  "dependencies": {
    "@rigor/design-tokens": "*"
  },
  "devDependencies": {
    "vitepress": "^1.0.0"
  }
}
EOF

cat > .vitepress/config.ts << 'EOF'
import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'RIGOR',
  description: 'AI Constraint Protocol — Normative Specification',
  
  appearance: 'dark',
  
  themeConfig: {
    logo: '/logo-rigor.svg',
    
    nav: [
      { text: 'rigor.dev', link: 'https://rigor.dev' },
      { text: 'Specification', link: '/specification/' }
    ],
    
    sidebar: {
      '/specification/': [
        {
          text: 'Protocol Specification',
          items: [
            { text: 'Identity Core', link: '/specification/identity-core' },
            { text: 'Protocol Model', link: '/specification/protocol-model' }
          ]
        }
      ]
    },
    
    socialLinks: [
      { icon: 'github', link: 'https://github.com/rigor' }
    ]
  }
})
EOF

cat > .vitepress/theme/index.ts << 'EOF'
import DefaultTheme from 'vitepress/theme'
import './custom.css'

export default DefaultTheme
EOF

cat > .vitepress/theme/custom.css << 'EOF'
@import '@rigor/design-tokens/css';

:root {
  --vp-c-bg: var(--color-bg-primary);
  --vp-c-bg-alt: var(--color-bg-secondary);
  --vp-c-text-1: var(--color-text-primary);
  --vp-c-text-2: var(--color-text-muted);
  --vp-c-brand-1: var(--color-accent);
  --vp-font-family-base: var(--font-body);
}
EOF

cat > index.md << 'EOF'
---
layout: home

hero:
  name: RIGOR
  text: AI Constraint Protocol
  tagline: Normative Specification
  actions:
    - theme: brand
      text: Read Specification
      link: /specification/
---
EOF

echo "   ✓ VitePress configured"

cd ../..

# ============================================
# STEP 7: Copy Assets
# ============================================
echo ""
echo "🖼️  Copying assets..."

BRIEF_PATH="../project-brief"

# Copy diagrams to web app
if [ -d "$BRIEF_PATH/4-assets/diagrams" ]; then
  cp "$BRIEF_PATH/4-assets/diagrams/"*.svg apps/web/public/diagrams/ 2>/dev/null || true
  cp "$BRIEF_PATH/4-assets/diagrams/logo-rigor-placeholder.svg" apps/web/public/favicon.svg 2>/dev/null || true
  echo "   ✓ Assets copied to web app"
else
  echo "   ⚠️  Warning: diagrams not found in project-brief"
fi

# Copy logo to docs app
if [ -f "$BRIEF_PATH/4-assets/diagrams/logo-rigor-placeholder.svg" ]; then
  cp "$BRIEF_PATH/4-assets/diagrams/logo-rigor-placeholder.svg" apps/docs/public/logo-rigor.svg
  echo "   ✓ Logo copied to docs app"
fi

# ============================================
# STEP 8: Install Dependencies
# ============================================
echo ""
echo "📥 Installing dependencies..."
echo "   (this may take a few minutes)"
echo ""

npm install

echo ""
echo "   ✓ Dependencies installed"

# ============================================
# STEP 9: Verify Setup
# ============================================
echo ""
echo "🔍 Verifying setup..."

# Check if key files exist
if [ -f "package.json" ] && \
   [ -f "turbo.json" ] && \
   [ -f "apps/web/package.json" ] && \
   [ -f "apps/docs/package.json" ] && \
   [ -f "packages/design-tokens/tokens.json" ]; then
  echo "   ✓ All critical files present"
else
  echo "   ✗ Some files missing - check logs above"
  exit 1
fi

# ============================================
# COMPLETE
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Project structure created at: $(pwd)"
echo ""
echo "Next steps:"
echo "  1. cd rigor"
echo "  2. npm run dev"
echo ""
echo "Expected output:"
echo "  - Landing: http://localhost:4321 (placeholder page)"
echo "  - Docs:    http://localhost:5173 (VitePress homepage)"
echo ""
echo "Now proceed to component implementation phase."
echo ""