#!/bin/bash
set -e

echo "🏗️  RIGOR — Project Setup"
echo "Generated by: Gemini Architect"
echo ""

# Step 1: Create directory structure
mkdir -p rigor/{apps/{web,docs},packages/design-tokens}
cd rigor

# Step 2: Create root package.json
cat > package.json << 'EOF'
{
  "name": "rigor-monorepo",
  "version": "0.1.0",
  "private": true,
  "workspaces": ["apps/*", "packages/*"],
  "scripts": {
    "dev": "turbo run dev",
    "build": "turbo run build"
  },
  "devDependencies": {
    "turbo": "latest"
  }
}
EOF

# Step 3: Create package.json for web app
cat > apps/web/package.json << 'EOF'
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview"
  },
  "devDependencies": {
    "astro": "latest",
    "tailwindcss": "latest",
    "@astrojs/tailwind": "latest"
  }
}
EOF

# Step 4: Create package.json for docs
cat > apps/docs/package.json << 'EOF'
{
  "name": "docs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vitepress dev",
    "build": "vitepress build",
    "preview": "vitepress preview"
  },
  "devDependencies": {
    "vitepress": "latest"
  }
}
EOF

# Step 5: Create package.json for design-tokens
cat > packages/design-tokens/package.json << 'EOF'
{
  "name": "design-tokens",
  "version": "0.1.0",
  "private": true,
  "main": "tailwind.config.js"
}
EOF

# Step 6: Create config files
cat > apps/web/astro.config.mjs << 'EOF'
import { defineConfig } from 'astro/config';
import tailwind from "@astrojs/tailwind";

// https://astro.build/config
export default defineConfig({
  output: 'static',
  integrations: [tailwind()],
  site: 'https://rigor.dev',
});
EOF

cat > apps/web/tailwind.config.mjs << 'EOF'
/** @type {import('tailwindcss').Config} */
import tokens from '../../packages/design-tokens/tailwind.config.js'

export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  presets: [tokens]
}
EOF

cat > turbo.json << 'EOF'
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
EOF

cat > packages/design-tokens/tailwind.config.js << 'EOF'
const tokens = {
  colors: {
    background: '#0A0A0A',
    surface: '#1C1C1C',
    'surface-tertiary': '#2A2A2A',
    text: '#F2F2F2',
    'text-muted': '#A3A3A3',
    accent: '#1E3A8A',
  },
  fontFamily: {
    heading: ['"IBM Plex Serif"', 'serif'],
    body: ['Inter', 'sans-serif'],
    mono: ['"JetBrains Mono"', 'monospace'],
  },
  letterSpacing: {
    wordmark: '0.08em',
  },
};

module.exports = {
  theme: {
    extend: {
      colors: tokens.colors,
      fontFamily: tokens.fontFamily,
      letterSpacing: tokens.letterSpacing,
    },
  },
};
EOF

# Step 7: Install dependencies
npm install

echo "✅  RIGOR — Project Setup Complete"
